import { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';

import newtClient from '@/libs/newt';

type Props = InferGetStaticPropsType<typeof getStaticProps>;

const Home: NextPage = ({ profile }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Portfolio Page</h1>
      <h3>{profile.enname}</h3>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const profile = await newtClient.getContents({
    appUid: 'bear29ers',
    modelUid: 'profile',
  });
  return {
    props: {
      profile: profile.items[0],
    },
  };
};

export default Home;
